### ISSUE TITLE
Helm Chart - Loader job only references MongoDB Secret and does not handle referencing internal secret if password specified

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/charts#80]

**Comment by tlawrie** [comment]
Currently:

```yaml
          {{- if $.Values.global.database.mongodb.secretName }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.global.database.mongodb.secretName }}
                key: mongodb-password
          {{- end }}
```

When should be:

```yaml
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if $.Values.global.database.mongodb.secretName }}{{ $.Values.global.database.mongodb.secretName }}{{ else }}{{ include "bmrg.name" (dict "context" $context "tier" "secrets" ) }}{{ end }}
                key: {{ if $.Values.global.database.mongodb.secretName }}mongodb-password{{ else }}MONGODB_PASSWORD{{ end }}
```
